### ISSUE TITLE
Interesse an deinem Github-Account/Nick

### ISSUE THREAD

**Issue by faulesocke** [socke/masterarbeit#1]
Hey,

ich benutze den Nick Socke praktisch überall und würde mich freuen, ihn auch auf Github benutzen zu können. Mir scheint, dass du deinen Github-Account nicht benutzt. Würde es dir etwas ausmachen, mir den Account/Nick zu überlassen? (Instruktionen würde ich nachreichen)

Grüße
Socke ;)

**Comment by socke** [comment]
Hallo,

danke für dein Interesse, aber ich muss höflich ablehnen. 

Viele Grüße
socke :-)
